const arrayConcierto=[
    
    {
        id:1 ,
        artista:"David Guetta",
        img:"https://noticiasargentinas.com/images/NA/Contenidos/1080x1080_px.jpg",
        imgslider:"https://noticiasargentinas.com/media/k2/items/cache/d870ef8774989efe8de527ee7562cc43_L.jpg?t=20221125_163559",
        estadoslider:"",
        estado:"",
        show:"El Sábado 17 de Diciembre en el horario de las 20:00 hs. sobre el prestigioso escenario del Teatro Ópera tenemos entonces una cita imperdible con su particular show.",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id: 2,
        artista:"Duki",
        img:"https://www.losandes.com.ar/resizer/ojsgsa851jV4s5dq7dVoB9zF-JM=/1023x1023/smart/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/XSYGGVBJOZFR7ITF6QJWAXSQXM.jpg",
        imgslider:"https://static6.ticketek.com.ar/cms_static/sites/default/files/images/show-header/duki_ticketek_960_x_400.png",
        estadoslider: "",
        estado:"",
        show:"El Sábado 25 de Diciembre en el horario de las 20:00 hs. sobre el prestigioso escenario del Teatro Ópera tenemos entonces una cita imperdible con su particular voz.",
        blog:"Mauro Ezequiel Lombardo Quiroga (Almagro, Buenos Aires, 24 de junio de 1996)conocido artísticamente como Duki, es un rapero y compositor argentino. Distinguido por su flow melódico y su utilización del autotune, es considerado la voz líder de la música trap en Argentina,​al ser además uno de los primeros artistas argentinos representando.",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id: 3,
        artista:"Dua Lipa",
        img:"https://fmlike.com.ar/wp-content/uploads/2020/11/123852513_171621364604153_3230785696513528073_n-1024x1024.jpg",
        imgslider:"https://www.infobae.com/new-resizer/cp_j_vh3_Ww1Kk6Wy4ONxNpp2pY=/1024x512/filters:format(webp):quality(85)//cloudfront-us-east-1.images.arcpublishing.com/infobae/RWE6HUH65ZGM7MKDUGFCTFU6FY.jpg",
        estado:"",
        estadoslider: "",
        show:"El Sábado 3 de Diciembre en el horario de las 20:00 hs. sobre el prestigioso escenario del Teatro Ópera tenemos entonces una cita imperdible con su particular voz.",
        blog:"Dua Lipa (Londres, 22 de agosto de 1995) es una cantante, compositora, modelo y actriz británica de origen albanokosovar. Después de trabajar como modelo, firmó con Warner Bros. Records en 2014 y lanzó su álbum debut homónimo en 2017. El álbum alcanzó el número 3 en la UK Albums Chart y lanzó ocho sencillos, incluidos «Be the One».",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id: 4,
        artista:"Tini",
        img:"https://pbs.twimg.com/media/FZrUsqJXwAAQRsl?format=jpg&name=large",
        imgslider:"https://www.totalmedios.com/img/noticias/2022/05/6287de237ba89__838x390.jpg",
        estado:"",
        estadoslider: "",
        show:"El Sábado 24 de Diciembre en el horario de las 20:00 hs. sobre el prestigioso escenario del Teatro Ópera tenemos entonces una cita imperdible con su particular voz.",
        blog:"Martina Stoessel1​ (Buenos Aires; 21 de marzo de 1997) conocida como Tini Stoessel o simplemente Tini, es una actriz, cantante y compositora argentina.Inició su carrera como actriz a los 10 años con un papel menor en la serie infantil Patito feo. Adquirió mayor reconocimiento tras ser protagonista en la telenovela Violetta, de Disney Channel Latinoamérica.",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:5 ,
        artista:"Bad Bunny",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyx9Gz0TdVuwW-dZujJqBEOgw8j2MV39aN7Q&usqp=CAU",
        imgslider:"http://www.lauriaweb.com/wp-content/uploads/2017/08/WhatsApp-Image-2017-08-17-at-11.48.36-1.jpeg",
        estado:"",
        estadoslider: "",
        show:"El Sábado 24 de Diciembre en el horario de las 20:00 hs. sobre el prestigioso escenario del Teatro Ópera tenemos entonces una cita imperdible con su particular voz.",
        blog:"Benito Antonio Martínez Ocasio (Almirante Sur, Vega Baja, 10 de marzo de 1994), conocido artísticamente como Bad Bunny, es un rapero, cantante, compositor, luchador y actor puertorriqueño.3​4​ Su estilo de música es generalmente definido como trap latino y reguetón, pero también ha interpretado otros géneros como kizomba.",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:6 ,
        artista:"Ricky Martin",
        img:"https://i.pinimg.com/474x/f7/52/76/f75276c088eba3dd3d702ea0a026e537.jpg",
        imgslider:"https://www.newsly.it/wp-content/uploads/2016/08/RICKY-Martin.jpg",
        estadoslider:"",
        estado:"",
        show:"El lunes 22 de Diciembre desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:7,
        artista:"Lali Esposito",
        img:"https://i.pinimg.com/474x/77/84/f6/7784f64340e98bfb84f25aadffe627ab.jpg",
        imgslider:"https://fotos.perfil.com/2022/11/01/trim/1140/641/asi-fue-el-look-de-lali-esposito-para-la-presentacion-de-el-fin-del-amor-1446501.jpg",
        estado:"",
        estadoslider:"",
        show:"El lunes 23 de Diciembre desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:8 ,
        artista:"Naty Peluso",
        img:"https://i.pinimg.com/236x/44/c2/14/44c21487c564db50e312ee8f6bd17e8f.jpg?nii=t",
        imgslider:"https://th.bing.com/th/id/OIP.kyoghc6_GmDgJXm-qS1-9wHaE7?pid=ImgDet&rs=1",
        estado:"",
        estadoslider:"",
        show:"El lunes 23 de enero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:9,
        artista:"Rusherking",
        img:"https://yt3.ggpht.com/P71uBduC0X05mraXo-p8l0CK7u7_h342QK5RyBgztmFwuEUmfE_540YBKpKh2BRik05d03zY=s900-c-k-c0x00ffffff-no-rj",
        imgslider:"https://th.bing.com/th/id/OIP.4OaXrvqrtvI8dUaqFXJEngHaEe?pid=ImgDet&rs=1",
        estado:"",
        estadoslider:"",
        show:"El Viernes 23 de enero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:10,
        artista:"Maria Becerra",
        img:"https://www.gente.com.ar/wp-content/uploads/2021/05/maria-becerra-.jpg",
        imgslider:"https://th.bing.com/th/id/OIP.b8ZNh9RxBKbh_gLgp-AZiwHaEc?pid=ImgDet&rs=1",
        estado:"",
        estadoslider:"",
        show:"El Viernes 15 de enero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:11,
        artista:"Angela Leiva",
        img:"https://i0.wp.com/www.disfrutarosario.com/wp-content/uploads/2020/01/angela-leiva-en-rosario.jpg?fit=400%2C400&ssl=1",
        imgslider:"https://img.lagaceta.com.ar/fotos/notas/2018/01/27/759472_20180127222053.jpg",
        estado:"",
        estadoslider:"",
        show:"El Viernes 5 de enero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id: 12,
        artista:"Miranda",
        img:"https://i.pinimg.com/originals/56/02/b8/5602b87524e17be0b1581b8879449266.jpg",
        imgslider:"https://th.bing.com/th/id/R.b5027c7aa22e30be7afd7188b1f3aafc?rik=bzkLhbfhN994Cg&riu=http%3a%2f%2f2.bp.blogspot.com%2f-N7os63dMjb0%2fVfXDUVeN0tI%2fAAAAAAAACFY%2f-OTbEdTOr68%2fs1600%2fmiranda-wallpapers-2.jpg&ehk=V63pE4bKydNBeXwl78gYJZ4YsmfV1l%2b5zR2LR7CdJzs%3d&risl=&pid=ImgRaw&r=0",
        estado:"",
        estadoslider:"",
        show:"El Viernes 12 de enero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id: 13,
        artista:"Ciro y los Persas",
        img:"https://i.pinimg.com/474x/46/70/72/4670724d595a1b0e1bfb9f624c2929a3.jpg",
        imgslider:"https://th.bing.com/th/id/OIP.HdL-qqaRasq9m2_VRI2LWQHaD4?pid=ImgDet&rs=1",
        estado:"",
        estadoslider:"",
        show:"El Viernes 23 de febrero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id: 14,
        artista:"Trueno",
        img:"https://i.pinimg.com/474x/52/0f/09/520f09ad0ceeaee515fcc190e171b0b8.jpg",
        imgslider:"https://i.ytimg.com/vi/45yJubCVIZY/maxresdefault.jpg",
        estado:"",
        estadoslider:"",
        show:"El Viernes 23 de febrero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    {
        id:15,
        artista:"Rosalia",
        img:"https://los40co00.epimg.net/los40/imagenes/2020/10/16/actualidad/1602871678_960558_1602871769_miniatura_normal.jpg",
        imgslider:"https://assets.soycarmin.com/__export/1608102563338/sites/debate/img/2020/12/16/rosalia_portada_revista_crop1608102403632.jpg_242310155.jpg",
        estado:"",
        estadoslider:"",
        show:"El domingo 23 de enero desde las 20:00 hs.En el Luna Park",
        blog:"Pierre David Guetta(París, 7 de noviembre de 1967) es un DJ, compositor y productor francés. Actualmente, ocupa el puesto #2 según la encuesta realizada por DJ Magazine.Se inició como tal en varias discotecas durante las décadas de 1980 y de 1990, antes de fundar Gum Productions y lanzar su primer álbum: Just a Little More Love (2002).",
        vip: 10.000,
        platea: 7.000,
        campo: 3.000
    },
    
]